### ISSUE TITLE
NY State income tax

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/policyengine-us#1082]
[Doc](https://docs.google.com/document/d/1m4VG3X4eJ8iS_uoSXn8K7qEhjJbl4Z-gz-yUFgFDh7U/edit)

[Legislation](https://www.nysenate.gov/legislation/laws/TAX/A22)

[Form](https://www.tax.ny.gov/pdf/current_forms/it/it201.pdf) ([instructions](https://www.tax.ny.gov/pdf/current_forms/it/it201i.pdf#page=25))

Computation tree:

- [ ] NY State income tax
  - [x] NY taxable income
    - [x] NY AGI
      - [x] Federal AGI
      - [x] NY AGI additions
      - [x] NY AGI subtractions
    - [x] NY standard deduction
    - [x] NY itemized deduction
    - [x] NY dependent exemptions
  - [x] NY tax before credits (including high-income alternative rates)
  - [x] NY non-refundable credits
    - [x] NY household credit
    - [x] NY resident credit
    - [x] NY other non-refundable credits
  - [ ] NY sales tax (? needs clarification)
  - [ ] NY refundable credits
    - [x] NY Empire State child credit
    - [x] #1244
    - [x] #1241
    - [x] #1243
    - [ ] NY real property tax credit
    - [ ] NY college tuition credit
    - [x] NY other refundable credits

**Comment by martinholmer** [comment]
@nikhilwoodruff,  Where do things stand on PEUS issue #1082 (which was opened over a year and a half ago)?  Is it useful to keep this issue open?

cc:  @MaxGhenis

**Comment by MaxGhenis** [comment]
Closing as we've moved to a different system for tracking state income tax completion (#993)
